PG-1013 Added build comparison table, moved features from index to comparison
percona/pg_tde pull request #280
Opened 2024-09-16 12:25 UTC by nastena1606

…mpaison

2024-09-23 10:44 UTC, dAdAbird commented on documentation/docs/features.md
> +* Logical replication support
Logical replication of encrypted tables works in Percona Server for PostgreSQL

2024-09-23 10:44 UTC, dAdAbird commented on documentation/docs/features.md
> +| Table encryption: <br> - data tables, <br> - TOAST tables <br> - temporary tables created during the database operation.<br><br> Metadata of those tables is not encrypted. | Index data encryption f
Regarding the encryption of TMP tables in Percona Server see https://perconadev.atlassian.net/browse/PG-1001. We didn't plan to have it, but might have accidentally done it)

2024-09-23 10:44 UTC, dAdAbird commented on documentation/docs/features.md
> +| PostgreSQL Community build  | Percona Server for PostgreSQL build <br> (in addition to features included in the PostgreSQL Community build)|
I'd duplicate everything we have for Community in Percona column. Having only additional features makes Percona Server looks less capable visually.

2024-09-23 13:49 UTC, nastena1606 commented on documentation/docs/features.md
> +| Table encryption: <br> - data tables, <br> - TOAST tables <br> - temporary tables created during the database operation.<br><br> Metadata of those tables is not encrypted. | Index data encryption f
Sorry i'm not following, what should be changed in the current wording?

2024-09-23 13:49 UTC, nastena1606 commented on documentation/docs/features.md
> +| PostgreSQL Community build  | Percona Server for PostgreSQL build <br> (in addition to features included in the PostgreSQL Community build)|
Done

2024-09-24 12:34 UTC, janwieremjewicz commented on documentation/docs/features.md
>  <i warning>:material-alert: Warning:</i> Note that introducing encryption/decryption affects performance. Our benchmark tests show less than 10% performance overhead for most situations. However, in
I think this needs to be clarified to make sure that the user knows which method do we relate to

2024-09-24 12:34 UTC, janwieremjewicz commented on documentation/docs/features.md
> -* Logical replication support
for which method?

2024-12-05 14:13 UTC, dAdAbird commented on documentation/docs/features.md
> +|                      | Global principal key management |
I'd skip "Global principal key management" in this table - it's a necessity for the full WAL encryption rather than a feature.

2024-12-05 14:17 UTC, dAdAbird commented on documentation/docs/features.md
> +| Table encryption: <br> - data tables, <br> - TOAST tables <br> - temporary tables created during the database operation.<br><br> Metadata of those tables is not encrypted. | Table encryption: <br>
I'd stress somehow "Index data for encrypted tables" (bold text or else) because this is the main reason we started this gig but currently, it's visually concealed among other things in the table

2024-12-05 14:33 UTC, dAdAbird commented on documentation/docs/release-notes/release-notes.md
> +* Added the `pg_tde_alter_principal_key_keyring('new-provider-name')`function, which copies the principal key to the specified new provider
Technically speaking, this function doesn't copy the key it just makes it possible to change the key's keyring provider. So the user would have to add a new provider (if it's not in the system yet) and copy the key there "manually" before calling this function...

2024-12-05 14:35 UTC, dAdAbird commented on documentation/docs/release-notes/release-notes.md
> +* JSON data is now handled with internal postgres JSON parser instead of jsonc
This is the same as "Keyring configuration now uses common JSON API. This simplifies code handling and enables frontend tools like `pg_waldump` to read the code thus improving debugging."

2024-12-05 15:15 UTC, nastena1606 commented on documentation/docs/features.md
> +|                      | Global principal key management |
Updated

2024-12-05 15:15 UTC, nastena1606 commented on documentation/docs/features.md
> +| Table encryption: <br> - data tables, <br> - TOAST tables <br> - temporary tables created during the database operation.<br><br> Metadata of those tables is not encrypted. | Table encryption: <br>
Good point. Updated, moved to the top in the list

2024-12-05 15:18 UTC, nastena1606 commented on documentation/docs/release-notes/release-notes.md
> +* Added the `pg_tde_alter_principal_key_keyring('new-provider-name')`function, which copies the principal key to the specified new provider
How to copy the key? I'm about to add this instrcution to the release notes item

2024-12-06 11:50 UTC, dAdAbird commented on documentation/docs/release-notes/release-notes.md
> +* Added the `pg_tde_alter_principal_key_keyring('new-provider-name')`function, which copies the principal key to the specified new provider
Currently, it is out of the scope of tde and depends on the keyring provider

2024-12-26 14:00 UTC, shahidullah79 requested changes
` Changed the location of internal TDE files: instead of the database directory, now all files are stored in `$PGDATA/tde``

It is $PGDATA/pg_tde instead of $PGDATA/tde

2024-12-26 15:13 UTC, dutow commented on documentation/docs/release-notes/release-notes.md
> +* Exposed Storage Manager API and added the usage of Initialization vector (IV) in it.
This sentence doesn't make sense here - the storage manager api is exposed by postgres, not pg_tde.

2024-12-26 16:10 UTC, dutow approved these changes

2024-12-26 16:14 UTC, merged

2024-12-27 13:55 UTC, shahidullah79 reviewed
LGTM