PG-1095 Add check CI workflow
percona/pg_tde pull request #308
Opened 2024-10-09 17:06 UTC by artemgavrilov

2024-10-11 13:33 UTC, artemgavrilov commented on .github/workflows/check.yaml
> +          ref: "2.13.4"
```suggestion
          ref: "2.15"
```

2024-10-11 13:34 UTC, artemgavrilov commented on .github/workflows/check.yaml
> +          ref: "2.15"
```suggestion
          ref: "2.15.0"
```

2024-10-11 14:29 UTC, artemgavrilov commented on .github/workflows/check.yaml
> +          cppcheck --enable=all --inline-suppr --template='{file}:{line},{severity},{id},{message}' --error-exitcode=1 --suppress=missingIncludeSystem --suppress=missingInclude --suppress=unmatchedSu
```suggestion
          cppcheck --enable=all --inline-suppr --template='{file}:{line},{severity},{id},{message}' --error-exitcode=1 --suppress=missingIncludeSystem --suppress=missingInclude --suppress=unmatchedSuppression:pg_tde.c .
```

2024-10-12 21:16 UTC, dutow requested changes
Generally looks good, but please exclude the versioned folders (`src16`, `src17`, and later any `srcXX`) from it.

The idea of them is that they only do minimal changes to the files copied from the server, to ensure that we can do minor/major version updates in an automated way using scripts.

Reformatting them would break this workflow.

If some lines/sections are completely added by us, reformatting them is okay, but this should be a manual process, not automated, because of the majority of the changes are done by sed. (the script doing this is in the `tools` directory)

2024-10-29 17:27 UTC, artemgavrilov commented
@dutow Done, `srcXX` folders are excluded from formatter

2024-10-31 10:51 UTC, dAdAbird approved these changes

2024-11-11 13:12 UTC, dutow approved these changes

2024-11-11 13:13 UTC, merged