PG-1013 Updated install steps for pg_tde
percona/pg_tde pull request #378
Opened 2024-12-11 16:20 UTC by nastena1606

PG-1013

### Description
The extension is now part of the server package, no need to install additional ones. Repo is no longer experimental

modified:   documentation/docs/apt.md
	modified:   documentation/docs/yum.md

2024-12-11 16:56 UTC, shahidullah79 requested changes
For pg_tde beta user need to enable 'testing' repo instead of experimental and release repos.  
 $ sudo percona-release enable ppg-{{pgversion17}} experimental
  $ sudo percona-release enable ppg-{{pgversion17}} testing

2024-12-12 06:43 UTC, ImTheKai commented on documentation/docs/apt.md
>      ```
Won't this be "main" after the release?

2024-12-12 07:15 UTC, shahidullah79 commented on documentation/docs/apt.md
>      ```
Currently for Beta we are using this. IMO after GA it will be move to main repo.

2024-12-16 07:25 UTC, dutow commented on documentation/docs/apt.md
>      ```
Won't we release the 17.2 package into the main repo, and just say that pg_tde in it is beta?

2024-12-16 10:22 UTC, shahidullah79 commented on documentation/docs/apt.md
>      ```
Yes it is part of server package then we need main/release repo to be configured.

2024-12-16 10:33 UTC, nastena1606 commented on documentation/docs/apt.md
>      ```
So what repo is the right one for 17.2 and the Beta?

2024-12-16 10:39 UTC, maqeel75 commented on documentation/docs/apt.md
>      ```
17.2

2024-12-16 12:19 UTC, nastena1606 commented on documentation/docs/apt.md
>      ```
Updated

2024-12-16 12:30 UTC, maqeel75 approved these changes

2024-12-16 14:34 UTC, shahidullah79 approved these changes

2024-12-16 14:54 UTC, maqeel75 approved these changes

2024-12-26 15:09 UTC, dutow approved these changes

2024-12-26 15:13 UTC, merged